modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="greamworks_tweaks"
version="${file.jarVersion}"
displayName="Greamworks Mod Tweaks"
description='''Gameplay integrations and targeted changes for mods without sufficient configuration hooks.'''

[[mixins]]
config="greamworks_tweaks.mixins.json"

[[dependencies.greamworks_tweaks]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.greamworks_tweaks]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.greamworks_tweaks]]
modId="dungeon_difficulty"
type="required"
versionRange="[3.6.10,4.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.greamworks_tweaks]]
modId="artifacts"
type="required"
versionRange="[13.2.1,14.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.greamworks_tweaks]]
modId="lootr"
type="required"
versionRange="[1.11.37,2.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.greamworks_tweaks]]
modId="critical_strike"
type="required"
versionRange="[1.0.4,2.0.0)"
ordering="AFTER"
side="BOTH"
